# Site
name: "Shivi's Food Blog (Under Construction)"
description: 'I like food.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
email: 'shivivats.dev@gmail.com'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    shivi:
      name:           Shivi
      site:           https://shivivats.github.io
      avatar:         /assets/images/avatar1.jpg
      bio:            "I like food."
      email:          shivivats.dev@gmail.com
      twitter:        https://twitter.com/shivivats7
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: shivi
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]